### ISSUE TITLE
hello...

### ISSUE THREAD

**Issue by Gyudori** [aliasgis/uostech#1]
저희가 과제를 제출하려고 하는데 이메일 주소를 모르겠어서 여쭤보려 글 남깁니다..

**Comment by aliasgis** [comment]
네 aloasgis75@uos.ac.kr 로 보내주세요 수고하셨어요

2019년 10월 21일 (월) 오후 3:18, Gyudori <notifications@github.com>님이 작성:

**Comment by aliasgis** [comment]
aliasgis@gmail.com

2019년 10월 21일 (월) 오후 10:19, Jiyoon Kim <aliasgis@gmail.com>님이 작성:
